-- =====================================================================
--  Effectifs de permanence et rôles de main courante — pour Cim'Log.
--
--  `statuts_mc` (rôles d'une section : PERMANENCIER, COS, NUIT…) vivait
--  jusqu'ici dans le projet Supabase de l'appli budget/commandes (CNEAS),
--  colonne `sections.statuts_mc`. Copié ici pour que Cim'Log les lise dans
--  le même projet que le reste (events/messages/sections/ref_secouristes) —
--  la colonne côté CNEAS sera supprimée une fois la bascule terminée.
--
--  Éditable depuis Cim'Log (onglet Effectifs) : chaque poste peut ajouter,
--  renommer ou retirer ses propres rôles, comme un secouriste ajouté à
--  ref_secouristes — pas de liste figée en dur dans le code.
--
--  `effectifs_mc` porte qui est affecté à quel rôle, jour par jour : une
--  ligne par personne (un rôle peut porter plusieurs noms, ex. « HUEZ » à
--  Grenoble). `secouriste_id` reste optionnel : un renfort d'une autre
--  section ne figure pas dans le ref_secouristes local, on garde alors
--  juste le nom saisi.
-- =====================================================================

BEGIN;

-- ---------- coordonnées des sections ----------
-- Rapatriées au passage depuis la même table côté CNEAS (adresse, ville,
-- téléphone) : pas encore utilisées par Cim'Log, mais utile à ranger tant
-- qu'on est déjà en train de lire cette base pour statuts_mc.
ALTER TABLE sections ADD COLUMN IF NOT EXISTS adresse_rue text;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS code_postal text;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS ville       text;
ALTER TABLE sections ADD COLUMN IF NOT EXISTS telephone   text;

UPDATE sections SET adresse_rue = '44 Avenue Rhin et Danube', code_postal = '38100', ville = 'GRENOBLE'
 WHERE code = 'CRS38' AND adresse_rue IS NULL;

UPDATE sections SET adresse_rue = '27F Rue Pasteur', code_postal = '05100', ville = 'BRIANCON', telephone = '0465585260'
 WHERE code = 'CRS05' AND adresse_rue IS NULL;

UPDATE sections SET adresse_rue = '38 chemin de la digue BP100', code_postal = '73200', ville = 'ALBERTVILLE'
 WHERE code = 'CRS73' AND adresse_rue IS NULL;

UPDATE sections SET adresse_rue = '396 Av. Pierre Sauvaigo', code_postal = '06700', ville = 'SAINT-LAURENT-DU-VAR'
 WHERE code = 'CRS06' AND adresse_rue IS NULL;

UPDATE sections SET adresse_rue = '526 Rue Carnot', code_postal = '65300', ville = 'LANNEMEZAN'
 WHERE code = 'CRS65' AND adresse_rue IS NULL;

UPDATE sections SET adresse_rue = '120 Av. Emile Roudayre', code_postal = '66000', ville = 'PERPIGNAN'
 WHERE code = 'CRS66' AND adresse_rue IS NULL;

-- ---------- rôles par section ----------
ALTER TABLE sections ADD COLUMN IF NOT EXISTS statuts_mc jsonb NOT NULL DEFAULT '[]'::jsonb;

UPDATE sections SET statuts_mc = '["COS", "PERMANENCIER", "SOM", "SOM OPJ", "SOP", "SOP OPJ", "VERSOUD", "NUIT", "HUEZ", "ASTREINTE COS"]'::jsonb
 WHERE code = 'CRS38' AND statuts_mc = '[]'::jsonb;

UPDATE sections SET statuts_mc = '["SoA1 7H", "SoA1 7H30", "SpA1 7H", "SoA1 8H", "SpA1 8H", "SoA1", "SpA1", "SoA1 11H", "SpA1 11H", "SoA1 13H", "SpA1 13H", "So RADIO", "Nuit", "MCA", "COS", "Chef Détachement"]'::jsonb
 WHERE code = 'CRS05' AND statuts_mc = '[]'::jsonb;

UPDATE sections SET statuts_mc = '["ASO", "BTS", "COS", "PERMANENCIER", "SMV"]'::jsonb
 WHERE code = 'CRS06' AND statuts_mc = '[]'::jsonb;

UPDATE sections SET statuts_mc = '["Albertville", "Modane", "Courchevel"]'::jsonb
 WHERE code = 'CRS73' AND statuts_mc = '[]'::jsonb;

-- Modifiable seulement par le poste lui-même, sur sa propre ligne — même
-- fonction `section_courante()` que le reste du cloisonnement (auth_rls.sql).
GRANT UPDATE (statuts_mc) ON sections TO authenticated;

DROP POLICY IF EXISTS maj_statuts_mc ON sections;
CREATE POLICY maj_statuts_mc ON sections
  FOR UPDATE TO authenticated
  USING (code = section_courante())
  WITH CHECK (code = section_courante());

-- ---------- effectifs du jour ----------
CREATE TABLE IF NOT EXISTS effectifs_mc (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_code   text NOT NULL REFERENCES sections(code),
  jour           date NOT NULL,
  role           text NOT NULL,
  nom            text NOT NULL,
  secouriste_id  bigint REFERENCES ref_secouristes(id),
  ordre          integer NOT NULL DEFAULT 0,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_effectifs_mc_jour ON effectifs_mc (section_code, jour);

ALTER TABLE effectifs_mc ENABLE ROW LEVEL SECURITY;

-- Même règle que les autres tables opérationnelles : le poste voit et gère
-- les effectifs de sa section et de ses postes rattachés (sections_visibles()).
DROP POLICY IF EXISTS par_section ON effectifs_mc;
CREATE POLICY par_section ON effectifs_mc
  FOR ALL TO authenticated
  USING (section_code = ANY (sections_visibles()))
  WITH CHECK (section_code = ANY (sections_visibles()));

GRANT SELECT, INSERT, UPDATE, DELETE ON effectifs_mc TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE effectifs_mc_id_seq TO authenticated;

COMMIT;

NOTIFY pgrst, 'reload schema';
